{
 "title": "Spotfinder",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{application=\"$application\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{route!=\"/metrics\"}[1m]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^2..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_usage{application=\"$application\"}[1m])*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(system_cpu_usage{application=\"$application\", instance=\"$instance\"}[1m])*100"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Request and Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{route!=\"/metrics\"}[1m]))",
     "legendFormat": "Total requests"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^2..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^5..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^4..$\", status!=\"^401$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^401$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "Unauthorised Errors Rate"
    }
   ]
  },
  {
   "title": "Requests per minute",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 7, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{route!=\"/metrics\"}[1m]))",
     "legendFormat": "Total requests (min)"
    }
   ]
  },
  {
   "title": "Average Response time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(rate(ktor_http_server_requests_seconds{route!=\"/metrics\"}[1m]))",
     "legendFormat": "Response time"
    }
   ]
  },
  {
   "title": "Top 10 APIs",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "topk(9, sort_desc(sum by(route, method) (ktor_http_server_requests_seconds_count{route!=\"/metrics\"})))",
     "legendFormat": "{{method}}  {{route}}"
    }
   ]
  },
  {
   "title": "Response time of 95% of requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/metrics\", quantile=\"0.95\"}[1m])",
     "legendFormat": "{{route}} 95%"
    }
   ]
  },
  {
   "title": "Response time of 90% of requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/metrics\", quantile=\"0.9\"}[1m])",
     "legendFormat": "{{route}} 95%"
    }
   ]
  },
  {
   "title": "Response time of 50% of requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(ktor_http_server_requests_seconds{instance=\"$instance\", route!=\"/metrics\", quantile=\"0.5\"}[1m])",
     "legendFormat": "{{route}} 50%"
    }
   ]
  },
  {
   "title": "Error Rates (per sec)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^5..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=\"^4..$\", status!=\"^401$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=~\"^401$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "Unauthorised Errors Rate"
    }
   ]
  },
  {
   "title": "Errors by API",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 24 },
   "targets": [
    {
     "expr": "topk(10, sort_desc(sum by(route, method, status) (ktor_http_server_requests_seconds_count{route!=\"/metrics\", status!=\"200\"})))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  },
  {
   "title": "New users",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{status=\"200\", route=\"/user\", method=\"POST\"}[1m]))",
     "legendFormat": "New users"
    }
   ]
  }
 ]
}